// Isolated integration checks: in-memory SQLite and simulated dispatch identities.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import { DatabaseSync } from 'node:sqlite';
import { z } from 'zod';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('drizzle/0000_same_scourge.sql','utf8').replaceAll('--> statement-breakpoint',''));
let who=null;
function statement(sql){let args=[];return {bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}}}
const db={prepare:statement,async batch(stmts){sqlite.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const server={db:()=>db,now:()=>new Date().toISOString(),fail:(message,status=400)=>{throw Object.assign(new Error(message),{status})},publicJourney:r=>{const {_meta,...data}=JSON.parse(r.data);return {...r,data:model.namespace.dataSchema.parse(data),meta:_meta||{}}}};
const ctx=vm.createContext({console:{error(){}},structuredClone,Response,Request,URL,crypto,Date,Set,Map,JSON,Object,String,Number,Array,Error});
const synth=(obj)=>new vm.SyntheticModule(Object.keys(obj),function(){for(const [k,v] of Object.entries(obj))this.setExport(k,v)},{context:ctx});
const model=new vm.SourceTextModule(ts.transpileModule(fs.readFileSync('lib/model.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText,{context:ctx});await model.link(()=>synth({z}));await model.evaluate();
const route=new vm.SourceTextModule(ts.transpileModule(fs.readFileSync('app/api/workspace/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText,{context:ctx});
await route.link(spec=>spec.endsWith('chatgpt-auth')?synth({getChatGPTUser:async()=>who}):spec.endsWith('server')?synth(server):spec.endsWith('model')?model:spec.endsWith('supervisor-guide')?synth({supervisorGuide:()=>({restricted:true})}):synth({default:JSON.parse(fs.readFileSync('lib/framework.json','utf8'))}));await route.evaluate();
const as=id=>{who=id?{userId:id,email:id+'@example.test',displayName:id}:null};
async function call(body,expect=200){const request=new Request('https://test.local/api/workspace',{method:'POST',headers:{Origin:'https://test.local','Content-Type':'application/json'},body:JSON.stringify(body)});const r=await route.namespace.POST(request),j=await r.json();assert.equal(r.status,expect,JSON.stringify(j));return j;}
async function get(query='',expect=200){const r=await route.namespace.GET(new Request('https://test.local/api/workspace'+query));const j=await r.json();assert.equal(r.status,expect,JSON.stringify(j));return j;}
as(null);await get('',401);as('hr');await call({action:'createWorkspace',name:'Test HTX'});
for(const [id,role]of [['officer','officer'],['manager','supervisor'],['other','officer']]){as('hr');const {code}=await call({action:'invite',role});as(id);await call({action:'join',code});as('replay');await call({action:'join',code},400)}
as('officer');await call({action:'invite',role:'admin'},403);const {id}=await call({action:'createJourney'});let j=(await get()).journeys[0];j.data.context='A QA-only conversation';j.data.selected=['excellence','care','transformation'];for(const key of j.data.selected)j.data.reflections[key]={...JSON.parse(JSON.stringify(model.namespace.emptyReflection)),rating:'Moderate extent',evidence:'Specific observed example'};
await call({action:'save',id,version:j.version,data:j.data,supervisorId:'manager'});as('manager');assert.equal((await get()).journeys.length,0);await get('?history='+id,403);as('hr');assert.equal((await get()).journeys.length,0);assert.equal((await get()).insights.suppressed,true);as('other');await call({action:'save',id,version:2,data:j.data},403);
as('officer');j=(await get()).journeys[0];await call({action:'share',id,version:j.version,data:j.data,supervisorId:'manager'});as('manager');j=(await get()).journeys[0];assert.equal(j.shared,1);const own=JSON.parse(JSON.stringify(j.data));own.reflections.care.evidence='Overwrite officer';await call({action:'save',id,version:j.version,data:own},403);
for(const key of j.data.selected)j.data.reflections[key].supervisorNote='I observed this in the launch discussion.';
j.data.reflections.excellence.supervisorRating='Large extent';j.data.actions=[{id:'action-one',attribute:'excellence',behaviour:'Delegate a quality check',opportunity:'Next release',success:'Colleague completes it independently',support:'Agree the standard together',date:'2026-10-15'}];await call({action:'save',id,version:j.version,data:j.data});await call({action:'save',id,version:j.version,data:j.data},409);
j=(await get()).journeys[0];await call({action:'endorse',id,version:j.version},400);as('officer');j=(await get()).journeys[0];j.data.agreement=true;await call({action:'save',id,version:j.version,data:j.data,supervisorId:'manager'});j=(await get()).journeys[0];await call({action:'endorse',id,version:j.version},403);
as('manager');j=(await get()).journeys[0];await call({action:'endorse',id,version:j.version});j=(await get()).journeys[0];assert.equal(j.status,'endorsed');assert.equal(j.data.reflections.excellence.rating,'Moderate extent');assert.equal(j.data.reflections.excellence.supervisorRating,'Large extent');const agreed=JSON.stringify(j.meta.agreedPlan);await call({action:'review',id,version:j.version,note:'Delegation worked. Maintain the agreed quality standard.'});j=(await get()).journeys[0];assert.equal(j.status,'endorsed');assert.equal(j.data.agreement,true);assert.equal(JSON.stringify(j.meta.agreedPlan),agreed);
assert.equal((await get('?prepare='+id)).guide.restricted,true);as('officer');await get('?prepare='+id,403);as('hr');await get('?prepare='+id,403);
as('manager');j=(await get()).journeys[0];await call({action:'suggest',id,version:j.version,attribute:'growth',reason:'Build others’ ownership through coaching.'});j=(await get()).journeys[0];assert.equal(j.meta.suggestions.length,1);assert.ok(!j.data.selected.includes('growth'));const suggestionId=j.meta.suggestions[0].id;await call({action:'respondSuggestion',id,version:j.version,suggestionId,response:'Add to our discussion'},403);
as('officer');j=(await get()).journeys[0];await call({action:'suggest',id,version:j.version,attribute:'growth',reason:'x'},403);await call({action:'respondSuggestion',id,version:j.version,suggestionId,response:'Discuss before deciding',note:'Let us connect it to the current action.'});j=(await get()).journeys[0];assert.equal(j.meta.suggestions[0].status,'Discuss before deciding');
j.data.selected=['excellence','care','growth'];j.data.focusDecisions={transformation:{status:'Paused',reason:'New assignment prioritises coaching',actionDisposition:'Paused with focus'}};j.data.changeReason='New assignment';j.data.agreement=false;await call({action:'save',id,version:j.version,data:j.data,supervisorId:'manager'});j=(await get()).journeys[0];assert.equal(j.status,'revision');assert.equal(j.meta.focus.transformation.status,'Paused');assert.equal(j.meta.focus.growth.status,'Proposed');assert.equal(JSON.stringify(j.meta.agreedPlan),agreed);assert.ok(j.data.reflections.transformation.evidence);
// A current action can support several selected attributes.
j.data.actions[0].also=['growth'];j.data.agreement=true;await call({action:'save',id,version:j.version,data:j.data,supervisorId:'manager'});as('manager');j=(await get()).journeys[0];await call({action:'endorse',id,version:j.version});j=(await get()).journeys[0];assert.equal(j.status,'endorsed');assert.equal(j.meta.focus.growth.status,'Active');assert.equal(j.meta.suggestions[0].status,'Included in agreed focus');assert.deepEqual(j.meta.agreedPlan.selected,['excellence','care','growth']);
// Restore the initial trio for the existing distinct-officer aggregate check.
as('officer');j=(await get()).journeys[0];j.data.selected=['excellence','care','transformation'];j.data.actions[0].also=[];j.data.focusDecisions.growth={status:'Moved on',reason:'Practice transferred',actionDisposition:'Completed with reflection'};j.data.changeReason='Returning to change adoption';j.data.agreement=false;await call({action:'save',id,version:j.version,data:j.data,supervisorId:'manager'});
as('hr');const hr=await get();assert.equal(hr.journeys.length,0);assert.equal(hr.insights.suppressed,true);await get('?history='+id,403);
for(let n=1;n<=4;n++){as('hr');const {code}=await call({action:'invite',role:'officer'});as('cohort-'+n);await call({action:'join',code});const created=await call({action:'createJourney'});const row=(await get()).journeys[0];row.data.selected=['excellence','care','transformation'];for(const key of row.data.selected)row.data.reflections[key]={...JSON.parse(JSON.stringify(model.namespace.emptyReflection))};await call({action:'share',id:created.id,version:row.version,data:row.data,supervisorId:'manager'});}
as('hr');const aggregate=(await get()).insights;assert.equal(aggregate.suppressed,false);assert.equal(aggregate.people,5);assert.equal(aggregate.themes.length,3);assert.ok(aggregate.themes.every(t=>t.count===5));assert.ok(!JSON.stringify(aggregate).includes('Specific observed example'));
as('outside');await call({action:'createWorkspace',name:'Different workspace'});assert.equal((await get()).journeys.length,0);await call({action:'review',id,version:j.version,note:'Unauthorized'},404);
console.log('PASS: sign-in gate, workspace invitations, invitation replay, private drafts, cross-user access, separate perspectives, stale saves, officer agreement, supervisor-only endorsement, preserved agreed snapshots, supervisor preparation access, suggestions, revisions, multiple action attributes, review history, HR privacy.');
