import { ArrowRight, ArrowUpRight, BookOpen, Compass, Flag, Heart, Lightbulb, MessageCircle, Sparkles, Target, Users, CheckCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
const traits=[{letter:'I',name:'Inspire',icon:Lightbulb},{letter:'D',name:'Dare to Try',icon:Flag},{letter:'E',name:'Empathise',icon:Heart},{letter:'A',name:'Aim High',icon:Target},{letter:'L',name:'Learn & Relearn',icon:Sparkles}];
export default function Home(){return <div className="ideal-landing">
<header className="landing-nav"><a href="/" className="landing-brand" aria-label="HTX IDEAL home"><img src="/htx-logo.png" alt="HTX" width="68" height="68"/><span>THE <strong>IDEAL</strong> WAY<small>GROWTH CONVERSATIONS</small></span></a><nav aria-label="Main navigation"><a href="#framework">The framework</a><a href="#journey">How it works</a><Button asChild className="nav-workspace"><a href="/journey">Open workspace <ArrowUpRight size={16}/></a></Button></nav></header>
<main><section className="landing-hero"><div className="hero-copy"><span className="landing-kicker"><span/> HTX LEADERSHIP FRAMEWORK</span><h1>Live the<br/><em>IDEAL</em> way.</h1><p className="hero-lead">Great leadership grows<br/>in everyday moments.</p><p className="hero-description">Turn a real work challenge into an honest conversation—and a practical next step. Discover the behaviours that help you and those around you thrive.</p><div className="hero-actions"><Button asChild><a href="/journey">Begin my journey <ArrowRight size={18}/></a></Button><a className="sample-link" href="/journey?sample=1">Explore a sample <ArrowUpRight size={17}/></a></div><div className="hero-footnote"><Users size={17}/><span>For every Xponent. At every leadership level.</span></div></div><div className="cover-composition"><img className="landing-cover" src="/ideal-cover.png" alt="The IDEAL Way: HTX Leadership Framework cover, featuring a driver racing through a vivid blue and purple futuristic track." width="1600" height="1237" fetchPriority="high"/><div className="cover-caption"><span>YOUR DIRECTION. YOUR GROWTH.</span><span>THE IDEAL WAY <ArrowUpRight size={14}/></span></div></div></section>
<section className="landing-traits" id="framework" aria-label="Five IDEAL traits">{traits.map(t=><a href="/journey?view=library" key={t.letter}><span className="landing-trait-letter">{t.letter}</span><div><t.icon size={20}/><strong>{t.name}</strong></div><ArrowUpRight className="trait-arrow" size={15}/></a>)}</section>
<section className="landing-how" id="journey"><div className="landing-section-heading"><div><span className="landing-kicker">A LITTLE FOCUS. MEANINGFUL GROWTH.</span><h2>Make the conversation count.</h2></div><p>You do not need to work on everything.<br/>Start with what matters most, then put it into practice.</p></div><div className="landing-cards"><article><div className="landing-card-top"><span className="landing-icon"><Compass size={25}/></span><span>01 / FIND YOUR FOCUS</span></div><h3>A few behaviours.<br/>A meaningful difference.</h3><p>Choose 3–5 attributes that connect to your current work, aspirations or feedback. Read the expectations for your leadership level.</p><div className="card-caption">15 attributes · 4 leadership levels</div></article><article><div className="landing-card-top"><span className="landing-icon"><MessageCircle size={25}/></span><span>02 / EXPLORE TOGETHER</span></div><h3>Bring your strengths.<br/>Stay curious.</h3><p>Prepare on your own or talk together. Explore where a strength helps, where it may be overplayed and what a different approach could unlock.</p><div className="card-caption">Your perspective + your supervisor’s</div></article><article><div className="landing-card-top"><span className="landing-icon"><CheckCheck size={25}/></span><span>03 / GROW THROUGH PRACTICE</span></div><h3>One or two actions.<br/>Real opportunities.</h3><p>Agree on practical actions, the support you need and a review date. Return to what you learned and decide what to try next.</p><div className="card-caption">Act · reflect · learn & relearn</div></article></div></section>
<section className="landing-bottom"><div className="bottom-icon"><BookOpen size={26}/></div><div><h2>One framework. A shared language for growth.</h2><p>Explore all five traits and the Lead Self, Grow Teams and Think Ecosystem dimensions.</p></div><Button asChild variant="outline"><a href="/journey?view=library">Explore IDEAL <ArrowRight size={17}/></a></Button></section></main>
<footer className="landing-footer"><a href="/" aria-label="HTX home"><img src="/htx-logo.png" alt="HTX" width="54" height="54"/></a><span>HTX · IDEAL Leadership Framework</span><a href="/IDEAL_Proposed_Edits_v2.pdf" target="_blank" rel="noreferrer">Read the framework <ArrowUpRight size={14}/></a></footer>
</div>}
