export const coaching:Record<string,{focus:string;over:string;under:string;experiment:string}>={
vision:{focus:'How did you connect a recent task to the outcome it serves?',over:'Could a compelling message be leaving too little room for questions or delivery detail?',under:'Where do people need more help understanding why their work matters?',experiment:'Open the next project discussion with the mission outcome; ask a colleague to describe the connection in their own words.'},
celebrate:{focus:'Whose contribution have you noticed, and what did you recognise specifically?',over:'Could frequent praise feel generic, or avoid an honest conversation about standards?',under:'Whose less visible effort might be going unnoticed?',experiment:'Recognise one specific contribution and explain its impact, using an approach the person welcomes.'},
influence:{focus:'Whose perspective changed your approach to a shared goal?',over:'Could securing agreement be taking priority over surfacing a legitimate concern?',under:'Where could a relationship beyond your immediate team help you contribute?',experiment:'Listen to one stakeholder with a different priority and agree on a shared outcome before proposing a solution.'},
experiment:{focus:'What assumption did you test, and what did the feedback change?',over:'Are new experiments crowding out learning, closure or responsible safeguards?',under:'Where is waiting for certainty preventing a small, safe test?',experiment:'Run one bounded test with a clear assumption, success signal and stopping rule; share what you learn.'},
resilience:{focus:'What helped you recover from a setback, and what support mattered?',over:'Could pushing through be concealing an unsustainable workload or a need for help?',under:'What would help you take the next manageable step after a setback?',experiment:'After the next setback, separate what you can influence from what needs support; agree one adjustment with your supervisor.'},
courage:{focus:'When did you voice a difficult perspective, and how did you make it useful?',over:'Could confidence or speed be closing down other perspectives?',under:'What concern or idea are you withholding, and what would make it easier to voice?',experiment:'Raise one concern early, describe the evidence and risk, then invite an alternative view before deciding.'},
care:{focus:'When did listening help you understand what someone actually needed?',over:'Could helping be becoming rescuing, avoiding accountability or stretching your own boundaries?',under:'Which unspoken concern might deserve a thoughtful check-in?',experiment:'Ask one open question, listen without immediately solving, and agree what support the person wants.'},
collaborate:{focus:'Where did adapting to another perspective improve the outcome?',over:'Could seeking consensus be slowing progress or blurring decision ownership?',under:'Who should be involved earlier, and what is making that difficult?',experiment:'Agree the shared outcome, decision owner and useful input with a partner team before the next milestone.'},
inclusion:{focus:'Whose voice was missing, and what did you do to invite it?',over:'Could keeping a discussion comfortable prevent a respectful challenge?',under:'What emotional cue or quieter perspective might you have missed?',experiment:'Invite written input before a meeting and ask whose perspective is absent before closing a decision.'},
excellence:{focus:'How did you define quality, test assumptions and focus on what mattered?',over:'Could attention to quality be delaying decisions or reducing others’ ownership?',under:'Which assumption, risk or quality expectation needs greater clarity?',experiment:'Agree what good enough looks like for one deliverable, test its riskiest assumption and set a decision deadline.'},
transformation:{focus:'What helped people adopt a new way of working?',over:'Could the pace of change be exceeding people’s capacity to absorb it?',under:'Where are you maintaining a process that no longer serves its purpose?',experiment:'Ask one affected colleague what blocks adoption, remove one barrier and check whether their day-to-day behaviour changes.'},
foresight:{focus:'What evidence and trade-offs informed a recent decision?',over:'Could anticipating every risk be delaying a proportionate, timely decision?',under:'Which longer-term consequence or stakeholder impact needs attention?',experiment:'Before a decision, write down two options, their trade-offs and one downstream consequence; seek guidance where needed.'},
growth:{focus:'What learning have you applied or shared in real work?',over:'Could gathering more learning be replacing practice or overloading development plans?',under:'What is preventing you from protecting time for one useful learning goal?',experiment:'Choose one skill, practise it in an upcoming task and ask someone for specific feedback.'},
agility:{focus:'When did feedback lead you to change your approach?',over:'Could constant adaptation be losing useful consistency or changing course too quickly?',under:'Which familiar approach is no longer working, and what could you unlearn?',experiment:'Try a different approach on one task, compare the outcome and decide what to retain.'},
digital:{focus:'Where did a digital or AI-enabled approach improve an outcome responsibly?',over:'Could enthusiasm for a tool be overlooking data safeguards, human judgement or the actual problem?',under:'What low-risk opportunity could build confidence with a useful tool?',experiment:'Trial an approved tool on a suitable task, verify its output and compare quality and effort with your existing approach.'}
};
export const probes=[{title:'Make change stick',text:'A new process, technology or way of working needs adoption.',ids:['transformation','care','digital']},{title:'Deliver with clarity',text:'Priorities, decisions or quality need sharper focus.',ids:['excellence','foresight','vision']},{title:'Work across boundaries',text:'Success depends on different people and perspectives.',ids:['collaborate','influence','inclusion']},{title:'Grow through uncertainty',text:'A stretch role, difficult setback or new challenge.',ids:['resilience','courage','agility']},{title:'Unlock team potential',text:'Help people learn, contribute and feel recognised.',ids:['growth','celebrate','care']}];
